name: pipeline-pandora-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-pandora-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install dependencies
        run: bundle install

      - name: Lint code
        run: rake lint
  job-pandora-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: rake test
